services:
  mongodb:
    image: mongo:8

    container_name: device-dashboard-mongodb

    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_DATABASE: device_dashboard

    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: